### ISSUE TITLE
Missing some fields on law metadata form

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/ckanext-odm_laws#102]
I notice that some fields have disappeared from law metadata form such as Issuing agency/parties and Implementing agencies.

**Comment by prustar** [comment]
@punwath -- I see the fields in CKAN. is this what you are referring to or in WP? 

![image](https://cloud.githubusercontent.com/assets/14996905/24998956/11947068-203c-11e7-844c-e982fdaa5501.png)

**Comment by punwath** [comment]
Yes it is. Sorry I was confused since it has been moved up.

**Comment by Huyeng** [comment]
@punwath, if so, can you close this issue?

**Comment by punwath** [comment]
Bong, I dont have any permission to close the issue.

**Comment by Huyeng** [comment]
No problem. Closed it now.
