### ISSUE TITLE
Request to private these 36 records of contract in law_record 

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/ckanext-odm_laws#107]
Most of these records are transferred into the agreement template, but several of them needs to change the document type. Thus, to avoid the duplicate the records on law page, please private them. 
Next, ODC team will update the document type for wrong document type of records.  After that, they will be removed from the CKan permanently.

Please ensure that only the contract of the law records are deleted, not records of contract in Agreement.
https://opendevelopmentcambodia.net/database/laws-policies-and-agreements?query=&taxonomy=all&group_type=laws_record&odm_document_type=contracts

**Comment by acorbi** [comment]
Hi @Huyeng, if I understand correctly, you want to me to **mark as private** following records that:

- are of type **laws records**
- have **contracts** as document types

The API call for retrieving those records is https://data.opendevelopmentmekong.net/api/3/action/package_search?fq=type:laws_record+extras_odm_document_type:contracts (totalling 36 records)

Please confirm

**Comment by acorbi** [comment]
I extracted the list of IDs from that API call: 

```
result__results__id
86f21efc-c910-4150-a5c1-f831815cba95
315c6f7d-caef-4a7e-bca7-189a86e1ab29
0648c004-3db6-4126-bb13-b1a24a41ba68
4b5a8fcb-0c06-4aa3-a6f0-99544819491c
43945ed7-9757-4771-9790-cfa777cccc8a
c9e51e16-c6aa-441e-81c1-8864785f72b6
0a83378f-07fd-4a2b-998d-6533c17345e7
34531ea5-c98f-4e8b-989b-b8f4f1cb7b37
192298b0-1623-446b-8aaf-55c837f3a0b9
7523fc8a-8f83-49f0-8d0f-9b57d1c599a6
4dbb6dc9-4998-4387-a236-68f48e8914bb
7e7f2012-68ab-471d-a72d-c3f63d22e99d
e70d69e2-fa6b-4589-87b5-a236b93ed47f
d6447c54-4496-40f5-bc0a-c4f52d0094a1
85b8cd65-0b4e-4084-8cf5-ebc9748f184d
d50d631a-454e-4951-a33b-0daa02cccbae
a263e06b-2d4c-4e68-bd2a-651825e58565
a67cf527-6050-4c6a-97ff-826933ac6f21
d8432751-2b8f-46a2-8fcd-ceccd6bd8771
2438199d-1cb4-42d6-88bf-1c6e165b217e
1527897d-bc08-4fbf-9533-556d52a4236f
ef3f04a5-7c3c-43a9-be9c-e783decc44b5
8cf2cf2c-b807-4695-bae0-30c129fd20cf
de4de4a8-1a91-4a59-9c0f-3564c4c99347
0d5f616b-d627-42af-9d83-17f10829c448
1cb769cf-7254-4b1e-b6a4-369a2f080c68
854488cd-e7a8-4ca0-a46f-cde3813b9c60
ec3ec07f-155a-49b4-8eb8-864fe16fdee0
8c7f14d3-1e13-45bd-b095-aa3718da59a6
72ac0887-363b-4964-b3c1-ea4cb3e1440b
0873a748-0fa8-408b-b5d5-1d4a600fa767
ca421f93-ee1a-48d8-8749-b4779036fd99
1c2c8e22-d177-436b-929b-be5abf7ca533
4922871d-07f8-4fb8-b856-f80703215b72
55896f32-8865-4929-8071-b464cc228dec
01a159bd-7eeb-486f-8848-3b82bcc37744
```

**Comment by Huyeng** [comment]
Yes, they are.

**Comment by acorbi** [comment]
@Huyeng done now via the scripts added on https://github.com/OpenDevelopmentMekong/data/commit/9c651c7ed33c083a443ba1449c2f95b0b5b1cc17
