### ISSUE TITLE
Show message when no relationships for dataset present

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/ckanext-odm_laws#11]
With 073553b4d6799bc9cc6567e7644035e617283ef9 relationship view for law dataset's that do not have a relationship set, is hidden.

It would be benifitial to the user-interface & -experience if the container would stay ( not change the position of the following containers), and state that there are no relationships set.

**Comment by acorbi** [comment]
Closing. not valid anymore.
