### ISSUE TITLE
The field "Issuing agency/parties" is not the mandatory field, but can't update if empty

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/ckanext-odm_laws#110]
![screenshot_1](https://user-images.githubusercontent.com/6613530/29549655-a8e3c924-8733-11e7-99bd-d65fa9c3f93c.jpg)

Some of law records, we don't know exactly the issuing agency/parties such as this record. Thus, the editor team would like to remove the royal_government_of_cambodia value from this record, but can't do it. 
https://data.opendevelopmentmekong.net/en/laws_record/constitutions-of-cambodia-2

**Comment by acorbi** [comment]
@Huyeng There are 2 things to consider around this issue:

1. All the mandatory fields should show the red asterisc (*) on the edit form. I have opened a PR that fixes this, see https://github.com/OpenDevelopmentMekong/ckanext-odm_laws/pull/111

2. It needs to be considered whether the **issuing agency/parties** should be mandatory or not. This is rather a non-technical question and would need to be coordinated with @prustar. In case you guys decide to make the field non-mandatory I can do the change pretty quickly.

**Comment by prustar** [comment]
@Huyeng -- it should be a mandatory field because someone signed the document and issued the policy/law/agreement etc. 

In the case of the constitution its the government or the sovereign of the state (i.e. the King). For Cambodia which is it? If it isn't in the list then we can add that easily to the table.

**Comment by Huyeng** [comment]
For the constitution, there are no information provided, so we can't define if the King or the government in the  issuing agency/parties field. Moreover, some of the draft records don't have the  issuing agency/parties information. 

If this field is set this as mandatory field, it will challenge for the editor team to policy the law records. 
My suggestion, please disable the mandatory field for this field right now. We can discuss later.
