### ISSUE TITLE
Specify placeholders for metadata fields

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_laws#16]
When creating a new Law record (https://pp-data.opendevelopmentmekong.net/laws_record/new) there are a big number of metadata fields that are missing a placeholder. This does not happen in dataset and library records.

![screenshot from 2016-01-04 17-33-49](https://cloud.githubusercontent.com/assets/384894/12094559/70a00a3c-b309-11e5-93fa-76b9aada0447.png)

It would be benefitial if the editorial team could come up with a table with the complete metadata definition and descriptions analog to https://wiki.opendevelopmentmekong.net/public:metadata#library_publications_metadata_template .

Once this table is defined on the wiki, new strings would be added to localization workflow in order to be translated and imported into the system.

**Comment by prustar** [comment]
@acorbi - This has been defined in this document - https://docs.google.com/document/d/1SubUAQmYWwFvyPgJLoE4IZauyMfh5l9fLfgQeF611QI/edit 

All the partners have contributed to the development of this and it should now be final. I will shortly do a comparison of what's changed in terms of the metadata template and send to you shortly.

**Comment by acorbi** [comment]
@prustar great, I will take those strings from the document when I implement this task. Please add corrections/modifications directly on the doc

**Comment by acorbi** [comment]
Done
