### ISSUE TITLE
Implement search box for law records on laws-page

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/ckanext-odm_laws#17]
Please implement single search box " Search in Laws "similar to https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/341

Placeholder text can stay on "search all laws"

![image](https://cloud.githubusercontent.com/assets/11522213/12114577/395d1e82-b3ab-11e5-8631-0dad22834a5e.png)

Search _agriculture & fishing_ & filter can be dismissed like in WP laws page

**Comment by acorbi** [comment]
This requirement is not valid anymore. closing
