### ISSUE TITLE
Move browse by topics bubbles into sidebar

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/ckanext-odm_laws#18]
Browse by topic bubbles should be moved to the sidebar on the right like in screenshot

![image](https://cloud.githubusercontent.com/assets/11522213/12114721/64543cfa-b3ac-11e5-88e2-ff4f5c243993.png)

**Comment by acorbi** [comment]
This requirement is not valid anymore, closing...
