### ISSUE TITLE
Note PREVIOUS 1 NEXT at end of each section

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/ckanext-odm_laws#23]
These seem very crunched together
![prev-1-next](https://cloud.githubusercontent.com/assets/16559612/12183554/722f0c3a-b55d-11e5-9b22-be1cda1a83cc.JPG)

**Comment by acorbi** [comment]
@jpeizer1 this needs to be moved to https://github.com/OpenDevelopmentMekong/opendev-wptheme and be tagged as PK2

**Comment by kathi-aeviator** [comment]
@jpeizer1 Please close this issue after moving
