### ISSUE TITLE
Show X Entries

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/ckanext-odm_laws#24]
![show-x-entries](https://cloud.githubusercontent.com/assets/16559612/12183563/7e6d9c46-b55d-11e5-97e9-0681cb828766.JPG)

The dropdown to show more than 10 entries doesn't seem to function. I change it to 25, etc in firefox and nothing happens -- I appreciate it simply may not be enough data to make the change but i don't see anything happening to indicate a state change.

**Comment by acorbi** [comment]
@jpeizer1 this needs to be moved to https://github.com/OpenDevelopmentMekong/opendev-wptheme and be tagged as PK2

**Comment by kathi-aeviator** [comment]
Not more needs. Closed issue. Please reopen if wrong.
