### ISSUE TITLE
Values created by date-picker control can not be deleted

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/ckanext-odm_laws#31]
Currently if a date is added to a field using the date picker control, it cannot be removed by using "backspace" or "delete" on the values. Is there another way to do it?

**Comment by acorbi** [comment]
@DBishton working on it...

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/commit/e3f5fdd0a41c9cfda5447c64dc90cc202c3d8d3d
