### ISSUE TITLE
Law 'relationship' fields contain limited options

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/ckanext-odm_laws#47]
Controls on the "Law, policies and agreements" metadata form for adding relationships:

Previous legal document
Associated document

display only a truncated list of options. Original spec was for "previous legal document" to display a list of all laws in the system, and "Associated document" a list of all possible document types in the system. 

@acorbi Can you investigate what is happening here and report back? Ideal functionality is to be discussed as part of @prustar's new spec.

**Comment by acorbi** [comment]
@DBishton @prustar Currently:

**Previous legal document** shows a list of 10 laws records. This can (and should) be changed in order to list all laws records, or at least allow the user to find a certain record using autocompletion.

**Associated document** has currently the same implementation as **Previous legal document**. Listing the different document types should be perfectly doable.

Can you guys find agreement on this and tell me what to implement? Thanks

**Comment by prustar** [comment]
@acorbi: 

**Previous legal document** should show all law records (or be able to find) the law that precedes it to create the relationship. But in this case then shouldn't we also have an option to view and select all legal documents that supersede it? 

**Associated documents** please clarify this - does it mean all legal documents or just other documents in general including any library record and/or dataset? Use case example: some sub-decrees, contracts and prakars list geospatial coordinates and maps for projects, these are used in development of the profile maps (i.e. ELCs)  thus it would be nice to link the user to that dataset. 

@DBishton throughts?

**Comment by acorbi** [comment]
@prustar Currently, the field **Associated documents** has the same behaviour as **Previous legal document** which is giving the user the opportunity to select ONE LAW RECORD (not library records or datasets) from a list of 10 items.

Please define the expected behaviour for both fields.

**Comment by prustar** [comment]
@acorbi This relates to this task in TWPM https://odinitiative.teamworkpm.net/tasks/6125497
I have just received the review back from ODC team and will append the Vietnam and Myanmar one when I get some feedback from them. After this then I can make a more reasonable assumption of how these relationships should work generally for the region and not just country specific. This will make managing the database easier.

**Comment by acorbi** [comment]
this should be now fixed in code deployed in PP currently
