### ISSUE TITLE
Law status update

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_laws#63]
@acorbi -- in the database clean up I'm requesting that all laws listed with an "unspecified" status be changed to "draft". This is because a law should have a status it is impossible that it is not specified, and if it is not directly specified then it is pending which we currently don't have a category for but will be an option in the new laws forms. We currently do not have categories for "cancelled" or "expired" either which might possibly be the case in some circumstances. 
- [x] Adapt migrations scripts done in https://github.com/OpenDevelopmentMekong/ckanext-odm_laws/issues/67.
- [x] Define mapping of old vs new values for odm_laws_status
- [x] Test migration scripts on PP.
- [x]  Run migration scripts on PROD.

**Comment by acorbi** [comment]
Done on data.staging.opendevelopmentmekong.net
