### ISSUE TITLE
Author/Maintainer: Removal of Fields

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_laws#64]
CKAN metadata fields: Maintainer, Maintainer Email, Author & Author Email shall not be shown to the public. This field may be better served for the internal use only, the back-end of the CKAN.

**Suggestion**: Only the field "Maintainer: Open Development Cambodia (ODC)" and "Maintainer email: info@opendevcam.net" may be shared with the public/users. 
![screenshot_3](https://cloud.githubusercontent.com/assets/10953792/18335491/eddb29ec-75a9-11e6-9413-23d64a279f35.jpg)

**Comment by prustar** [comment]
@acorbi - the last time I was looking at this the logic of the maintainer and the author was curious to me. When an overall editor is uploading a dataset they should be the author and addition publication and edits should be credited to the maintainer. In this way we always know who originally uploaded the datasets but any number of people can be the maintainer if datasets need editing over time.

**Comment by acorbi** [comment]
@prustar that is the expected and implemented behaviour. closing this issue
