### ISSUE TITLE
Metadata fields disappear when a law dataset is edited

### ISSUE THREAD

**Issue by thetaung2** [OpenDevelopmentMekong/ckanext-odm_laws#72]
Information filled in the following fields disappear when that dataset is edited:
Issuing agency/parties
Implementing agencies
Formal type of document
Status went back to "under negotiation"
 
So a user has to add these info: again.

**Comment by acorbi** [comment]
@thetaung2 this is now fixed and deplyoed on PP. Please check the records you added and re-open in case it does not work as you expect.
