### ISSUE TITLE
Strange URL for this Law on ODMm

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_laws#81]
This Myanmar law URL is strange it doesn't match the title of the law which is "The Fertilizer Law"?
![image](https://cloud.githubusercontent.com/assets/14996905/20913255/34551390-bbca-11e6-81eb-fb733495d0a0.png)

@thetaung2 can you please check. 

- Why does this record has this URL? 
- Can you please change it to an appropiate value?

**Comment by acorbi** [comment]
@thetaung2 @prustar I noticed this record is only available on PP with that URL. @thetaung2 is the record available on PROD (http://data.opendevelopmentmekong.net)?

**Comment by thetaung2** [comment]
@acorbi @prustar  We've only uploaded the laws in pp site. Not on the PROD.

**Comment by prustar** [comment]
@thetaung2 -- then I'm going to close this issue if it's only in PP.
